#!/usr/bin/env bash
#
# #synopsis:
# Shows dotmate version number
# #description:
# Displays the version number of this dotmate release.
# #usage:
# #
#

dotmateversion() {
	local version=$(cat ${basedir}/version)
	printf "%s %s\n" "${basename}" "${version}"
}

isrunning "dotmate-version" "dotmate---version" "dotmate--v" && dotmateversion "$@"

