#!/usr/bin/env bash
#
# #synopsis:
# Describe command line options and commands
# #description:
# Dotmate helps you manage "dotfiles", your personal settings
# stored in multiple hidden files under your home directory.
# #usage:
# command
# #
#

this=$(readlink -f "$0")
export basename=$(basename "$this")
export dirname=$(dirname "$this")
export basedir=$(cd "$dirname" && pwd)
cd $(dirname "$dirname")

if [ -t 1 ]
then
	export colorbold=$(tput bold)
	export colorred=$(tput setaf 1)
	export coloryellow=$(tput setaf 3)
	export colorgreen=$(tput setaf 2)
	export colordefault=$(tput sgr0)
	export clearline=$(tput el 1)
else
	export colorbold=""
	export colorred=""
	export coloryellow=""
	export colordefault=""
	export clearline=""
fi

notify() {
	local error="$1"
	shift
	printf "${coloryellow}** ${error}${colordefault}\n" "$@" >&2
}
export -f notify

complain() {
	local error="$1"
	shift
	printf "${colorred}!! ${error}${colordefault}\n" "$@" >&2
}
export -f complain

die() {
	local error="$1"
	shift
	printf "${colorred}!! ${error}${colordefault}\n/exiting/\n" "$@" >&2
	exit 100
}
export -f die

isrunning() {
	local actual=$(basename "$0")
	while [ $# -gt 0 ]
	do
		local expected="$1"
		if [ "$expected" == "$actual" ]
		then
			return 0
		fi
		shift
	done
	return -1
}
export -f isrunning

if [ -z "$DOTMATE_DEBUG" ]
then
	debug() {
		return #no-op
	}
else
	debug() {
		printf "$@" >&2
	}
fi
export -f debug

command="$1"
shift
args="$@"
if [ -z "$command" ]
then
	command="help"
elif [ "$command" == "help" ] && [ $# -lt 1 ]
then
	args="help"
fi
debug "running dotmate command: %s in dir %s\n" $command $(pwd)
execpath=${basedir}/${basename}-${command}
if [ ! -x "$execpath" ]
then
	die "unknown command '%s'" $command
fi
exec $execpath $args

