#!/usr/bin/env bash
#
# #synopsis:
# Create or update symlinks to dotmate output directory
# #description:
# Creates symlinks in user's home directory leading to generated dotfiles in dotmate output directory.
# 
# --dry-run run without performing any changes.
# --home    uses the given path as home directory.
# #usage:
# [--dry-run|--home path]
# #
#

dotmatelink() {
	local hdir=$HOME
	local dryrun=""
	local out="out"
	local switch="$1"

	case "$switch" in
	"--dry-run" )
		dryrun=1
		shift
		;;
	"--home" )
		hdir="$2"
		shift 2
		;;
	"" )
		;;
	* )
		die "unknown switch '$switch'"
		;;
	esac

	local files=$(find $out/ -type f -printf '%P\n')
	for file in $files
	do
		debug "processing: %s dryrun=%s hdir=%s\n" "$file" "$dryrun" "$hdir"
		local fb=$(basename $file)
		local fd=$(dirname $file)
		debug "mkdir %s\n" $hdir/$fd
		[ -z $dryrun ] && mkdir -p $hdir/$fd
		local target=$hdir/$file
		if [ ! -e $target ] || [ -L $target ]
		then
			debug "ln %s %s\n" "$out/$file" "$target"
			outbase=$(pwd)
			[ -z $dryrun ] && ln -sf "$outbase/$out/$file" "$target"
		else
			notify "%s exists, skipping" $target
		fi
	done
	debug "linking done\n"
}

isrunning "dotmate-link" && dotmatelink "$@"

