#!/usr/bin/env bash
#
# #synopsis:
# Describe command line options and commands
# #description:
# Displays a description of dotmate commands listed as parameters.
# 
#       --usage  displays the possible command line parameters and options
#       --short  displays only the synopsis
# --description  displays only the description
#        --full  displays command synopsis, usage and full description
# 
# With no options given, displays usage and description.
# With no commands given, displays description for "help" command.
# #usage:
# [--usage|--short|--full] command...
# #
#

catcut() {
 	cat $1 | sed -n 's/^# \(.*\)$/\1/mp' | sed -n "/#$2:/,/#/{//!p;}"
}

printhelp() {
	if [ ! -x "$1" ]
	then
		die "unknown command '$command'"
	fi
	if [ -n "$synopsis" ]
	then
		text=$(catcut $1 'synopsis')
		textlen=$(echo $text | wc -l)
		if [ $textlen -gt 0 ]
		then
			printf "${colorbold}%15s${colordefault}  %s\n" \
				$command "$text"
		fi
	fi
	if [ -n "$usage" ]
	then
		text=$(catcut $1 'usage')
		textlen=$(echo $text | wc -l)
		if [ $textlen -gt 0 ]
		then
			printf "Usage:\n  %s ${colorbold}%s${colordefault} %s\n\n" \
				$basename $command "$text"
		fi
	fi
	if [ -n "$description" ]
	then
		text=$(catcut $1 'description')
		textlen=$(echo $text | wc -l)
		if [ $textlen -gt 0 ]
		then
			printf '%s\n\n' "$text"
		fi
	fi
}

dotmatehelp() {
	local usage=1
	local synopsis=
	local description=1

	local switch="$1"
	case "$switch" in
	"--usage" )
		usage=1
		synopsis=
		description=
		shift
		;;
	"--short" )
		usage=
		synopsis=1
		description=
		shift
		;;
	"--full" )
		usage=1
		synopsis=1
		description=1
		shift
		;;
	"--description" )
		usage=
		synopsis=
		description=1
		shift
		;;
	"--"* )
		die "unknown switch '$switch'"
		;;
	esac

	if [ $# -lt 1 ]
	then
		local versionpath=${basedir}/${basename}-version
		source "$versionpath"
		dotmateversion
		echo
		execpath=${basedir}/${basename}
		printhelp $execpath
		echo "Try \"dotmate commands\" or \"dotmate help\""
		echo
		#helppath=${basedir}/${basename}-help
		dotmatehelp --short commands help
	fi

	while [ $# -gt 0 ]
	do
		command="$1"
		execpath=${basedir}/${basename}-${command}
		printhelp $execpath
		shift
	done
}

isrunning "dotmate-help" "dotmate---help" "dotmate--h" && dotmatehelp "$@"

