#!/usr/bin/env bash
#
# #synopsis:
# Lists all available dotmate commands
# #description:
# Useful remembering what are the possible things dotmate can do you for.
# #usage:
# #
#

dotmatecommands() {
	local basenamelen=$(($(echo $basename | wc -c) + 1))
	local commands=$(find ${basedir}/ -type f -name ${basename}-* -executable -printf '%f\n' | cut -c ${basenamelen}- | sort)
	local helppath=${basedir}/${basename}-help
	source "$helppath"
	for command in "$commands"
	do
		dotmatehelp --short "$command"
	done
}

isrunning "dotmate-commands" && dotmatecommands "$@"

